version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR.... 
    - aws --version
    #- eval $(aws ecr get-login-password --no-include-email --region ap-southeast-1)
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 101614871148.dkr.ecr.ap-southeast-1.amazonaws.com
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    # Replace with your application name
    - APPLICATION_NAME=tradewatchlistservice
    # Replace with this 435320931996.dkr.ecr.ap-south-1.amazonaws.com to your repository URI
    - REPOSITORY_URI=101614871148.dkr.ecr.ap-southeast-1.amazonaws.com/tradewatchlistservice
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image...
    - docker build -t $APPLICATION_NAME:$IMAGE_TAG .
    - docker tag $APPLICATION_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repository
    - echo repo $REPOSITORY_URI:$IMAGE_TAG
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file... 
    # Give your container name
    - printf '[{"name":"tradewatchlistecsservice", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
